spring:
  jpa:
    show-sql: true # DDL 출력
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser
    boot:
      admin:
        client:
          url: http://localhost:8080
          instance:
            service: http://localhost:8080
