server:
  port: 8888    # Config Server가 수신 대기하는 포트

spring.cloud.config.server:
  encrypt.enabled: false
  git:
    uri: https://github.com/holicker/microservice
    searchPaths: config-repository

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: "ALWAYS"
